import type { IdeaReport, NewsItem, FundamentalsSnapshot } from '../types';

export function generateMarkdown(report: IdeaReport): string {
  const sections = [
    `# Investment Analysis: ${report.source.title || 'Untitled'}`,
    `\n> ⚠️ **Disclaimer**: Educational only - Not financial advice`,
    `\n**Source**: [${report.source.url}](${report.source.url})`,
    `**Generated**: ${formatDate(report.created_at)}`,
    `\n## Executive Summary\n\n${report.executive_summary.map((s) => `- ${s}`).join('\n')}`,
    `\n## Tickers\n\n${report.tickers.map((t) => `- **${t.symbol}** (${t.company_name}) - Confidence: ${Math.round(t.confidence * 100)}%`).join('\n') || 'No tickers identified'}`,
    `\n## Investment Thesis\n\n${report.thesis}`,
    `\n## Supporting Quotes\n\n${report.rationale_quotes.map((q) => `> "${q.quote}"`).join('\n\n') || 'No supporting quotes'}`,
    `\n## Catalysts\n\n${report.catalysts.map((c) => `- ${c}`).join('\n') || 'None identified'}`,
    `\n## Risks\n\n${report.risks.map((r) => `- ⚠️ ${r}`).join('\n') || 'None identified'}`,
    `\n## Counter-Thesis\n\n${report.counter_thesis}`,
    `\n## Confidence\n\n**Score**: ${Math.round(report.confidence_score * 100)}%\n\n${report.confidence_explanation}`,
    `\n## Time Horizon\n\n${report.horizon}`,
    `\n## Limitations\n\n${report.limitations.map((l) => `- ${l}`).join('\n') || 'None identified'}`,
  ];

  if (report.news_context?.length) {
    sections.push(`\n## News Context\n\n${formatNewsMarkdown(report.news_context)}`);
  }
  if (report.fundamentals_summary?.length) {
    sections.push(`\n## Fundamentals\n\n${formatFundamentalsMarkdown(report.fundamentals_summary)}`);
  }
  if (report.cross_reference_analysis) {
    const xref = report.cross_reference_analysis;
    const parts: string[] = [];
    if (xref.convergences?.length) {
      parts.push(`### Convergences\n\n${xref.convergences.map((c) => `- ${c}`).join('\n')}`);
    }
    if (xref.divergences?.length) {
      parts.push(`### Divergences\n\n${xref.divergences.map((d) => `- **${d.topic}**: ${d.source_a} says "${d.finding_a}" vs ${d.source_b} says "${d.finding_b}" — ${d.explanation}`).join('\n')}`);
    }
    if (xref.deduplicated_risks?.length) {
      parts.push(`### Deduplicated Risks\n\n${xref.deduplicated_risks.map((r) => `- ⚠️ ${r}`).join('\n')}`);
    }
    if (parts.length) sections.push(`\n## Cross-Reference Analysis\n\n${parts.join('\n\n')}`);
  }
  if (report.macro_context) {
    const m = report.macro_context;
    const parts = [`**Sector**: ${m.sector}`];
    if (m.sector_trends?.length) parts.push(`**Trends**:\n${m.sector_trends.map((t) => `- ${t}`).join('\n')}`);
    if (m.economic_indicators?.length) parts.push(`**Indicators**:\n${m.economic_indicators.map((i) => `- ${i}`).join('\n')}`);
    if (m.headwinds?.length) parts.push(`**Headwinds**:\n${m.headwinds.map((h) => `- ⚠️ ${h}`).join('\n')}`);
    if (m.tailwinds?.length) parts.push(`**Tailwinds**:\n${m.tailwinds.map((t) => `- ✅ ${t}`).join('\n')}`);
    sections.push(`\n## Macro Context\n\n${parts.join('\n\n')}`);
  }

  if (report.thinking_output) {
    const entries = Object.values(report.thinking_output);
    if (entries.length > 0) {
      const thinkingParts = entries.map((e) => `### ${e.agent_id} (${e.phase})\n\n${e.content}`).join('\n\n');
      sections.push(`\n<details><summary>Thinking Process</summary>\n\n${thinkingParts}\n\n</details>`);
    }
  }
  sections.push(`\n---\n\n*Generated by Text2Invest using ${report.provider_meta.provider}/${report.provider_meta.model}*\n`);
  return sections.join('\n');
}

function formatNewsMarkdown(items: NewsItem[]): string {
  return items.map((item) =>
    `- **[${item.headline}](${item.url})** (${item.source}, ${item.published_date})\n  Sentiment: ${item.sentiment} | Relevance: ${Math.round(item.relevance_score * 100)}% | Source: ${item.data_source === 'web_search' ? 'Web' : 'LLM'}\n  ${item.summary}`
  ).join('\n\n');
}

function formatFundamentalsMarkdown(snapshots: FundamentalsSnapshot[]): string {
  return snapshots.map((snap) => {
    const header = `### ${snap.ticker} - ${snap.company_name} (${snap.data_source === 'web_search' ? 'Web' : 'LLM'})`;
    const table = snap.metrics.length
      ? `| Metric | Value | Period |\n|--------|-------|--------|\n${snap.metrics.map((m) => `| ${m.name} | ${m.value} | ${m.period || '-'} |`).join('\n')}`
      : 'No metrics available';
    return `${header}\n\n${table}`;
  }).join('\n\n');
}

export function generateJSON(report: IdeaReport): string {
  const exportData = {
    ...report,
    disclaimer: 'Educational only - Not financial advice',
    exported_at: new Date().toISOString(),
  };
  return JSON.stringify(exportData, null, 2);
}

export function downloadFile(filename: string, content: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function formatDate(dateStr: string): string {
  try {
    return new Date(dateStr).toLocaleDateString(undefined, {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  } catch {
    return dateStr;
  }
}
