import type { IdeaReport } from '../types';

export function generateMarkdown(report: IdeaReport): string {
  return `# Investment Analysis: ${report.source.title || 'Untitled'}

> ⚠️ **Disclaimer**: Educational only - Not financial advice

**Source**: [${report.source.url}](${report.source.url})
**Generated**: ${formatDate(report.created_at)}

## Executive Summary

${report.executive_summary.map((s) => `- ${s}`).join('\n')}

## Tickers

${report.tickers.map((t) => `- **${t.symbol}** (${t.company_name}) - Confidence: ${Math.round(t.confidence * 100)}%`).join('\n') || 'No tickers identified'}

## Investment Thesis

${report.thesis}

## Supporting Quotes

${report.rationale_quotes.map((q) => `> "${q.quote}"`).join('\n\n') || 'No supporting quotes'}

## Catalysts

${report.catalysts.map((c) => `- ${c}`).join('\n') || 'None identified'}

## Risks

${report.risks.map((r) => `- ⚠️ ${r}`).join('\n') || 'None identified'}

## Counter-Thesis

${report.counter_thesis}

## Confidence

**Score**: ${Math.round(report.confidence_score * 100)}%

${report.confidence_explanation}

## Time Horizon

${report.horizon}

## Limitations

${report.limitations.map((l) => `- ${l}`).join('\n') || 'None identified'}

---

*Generated by Text2Invest using ${report.provider_meta.provider}/${report.provider_meta.model}*
`;
}

export function generateJSON(report: IdeaReport): string {
  const exportData = {
    ...report,
    disclaimer: 'Educational only - Not financial advice',
    exported_at: new Date().toISOString(),
  };
  return JSON.stringify(exportData, null, 2);
}

export function downloadFile(filename: string, content: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function formatDate(dateStr: string): string {
  try {
    return new Date(dateStr).toLocaleDateString(undefined, {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  } catch {
    return dateStr;
  }
}
